### ISSUE TITLE
Multiple values are not allowed for plugin option androidx.compose.compiler.plugins.kotlin:generateDecoys

### ISSUE THREAD

**Issue by hfhbd** [cashapp/molecule#134]
If you apply Jetbrains compose plugin manually too, this js build fails because generateDecoys is provided twice for JS (with the same value).
Small reproducer coming soon, sample app: https://github.com/hfhbd/ComposeTodo/pull/665/files
Workaround: just don't use this gradle plugin and depend on the runtime manually

**Comment by JakeWharton** [comment]
Hmm maybe we should detect the presence of that plugin and fail the build saying you only need one.
