### ISSUE TITLE
IDE does not resolve dependency added by molecule plugin in Common source set

### ISSUE THREAD

**Issue by igorbzin** [cashapp/molecule#136]
I have tried to include the molecule plugin in my KMM project, but even after applying the plugin, it seems that the dependency is not added properly to all sourceSets. I have done some further research and the issue very similar to this issue opened here:

https://youtrack.jetbrains.com/issue/KTIJ-18425/

with the difference, that it uses "implementation" instead of "compileOnly".

I opened a new issue here with a minimal project for reproducing attached:

https://youtrack.jetbrains.com/issue/KTIJ-23680/IDE-does-not-resolve-dependency-added-by-KotlinCompilerPluginSupportPlugin-in-Common-code

Until this is resolved, you will have to add 

               implementation("app.cash.molecule:molecule-runtime:0.6.0")

manually to the shared module build.gradle to make Molecule work in KMM projects.

**Comment by JakeWharton** [comment]
Should be fixed by 20e36199c2a2226e21fee9b598122aab6358e938 which now adds the runtime at the project-level rather than per-compilation.

**Comment by JakeWharton** [comment]
Nevermind wrong project. We need to do that here.
