### ISSUE TITLE
Multiplatform support

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/molecule#2]
Shipped:
- [x] Android (all versions)
- [x] JS (0.3.0 and newer)
- [x] JVM (0.3.0 and newer)

Blocked:
- [ ] iOS (waiting for JB runtime 1.2.0)
- [ ] MacOS (waiting for JB runtime 1.2.0)
- [ ] tvOS (waiting for JB runtime 1.2.0)
- [ ] watchOS (waiting for JB runtime 1.2.0)
- [ ] Linux (waiting for JB runtime 1.2.0)
- [ ] Windows (waiting for JB runtime 1.2.0)

**Comment by eygraber** [comment]
In Multiplatform Compose and Gradle module metadata abuse you mention that Google is probably far off from doing this, and best bet is for JetBrains to handle it for now. Is there any public discussion about it on their end?

If JetBrains isn't going to do it, (or if it will take them a while), would it be possible to have a community "standard" artifact that mirrors and shades Google's?

**Comment by JakeWharton** [comment]
I have no idea if JetBrains is thinking about fixing Google's mistake / lack of action in this space. But aside from Google, JetBrains is the _only_ company which can do this seeing as they currently publish a version of the runtime for JVM and JS. They would have to unify these into a single multiplatform build, ship versions which align directly with Google's binaries, and have the Gradle module metadata point at Google's artifact.

Any third-party multiplatform build of the runtime will be impossible to use with Compose for Desktop/Web and Compose UI for Android given that JetBrains and Google do not ship from the same SHAs. You would have to convince JetBrains to change their Compose for Desktop and Compose for Web products to point at this third-party build which seems impossible given that they're currently forks and ship with wildly different cadences to each other and to Google's Compose.

**Comment by eygraber** [comment]
I'm guessing this would be a big no (because of complexity and scalability) but what about writing molecule in common Kotlin, and then delegating the compose implementation to the targets?

Then for each target there could be multiple artifacts corresponding to the runtime being used if necessary. That would address the issue of different SHAs because the consumer would be explicitly saying that they want the artifact with a runtime based on Compose UI, Compose Desktop, Compose Redwood, etc...

Then if Google or JetBrains ever releases a multiplatform artifact those could all be deprecated. 

It would be a step backwards from how KMP works with dependencies, but Molecule would be able to be used in common code. 

_I'm working on very little sleep so take this all with a very big grain of salt_

**Comment by JakeWharton** [comment]
It's not just the runtime, though, you also have to have a matching version of the compiler. If you want to support native you have to have a different build of the compiler than the other platforms due to a binary incompatibility between the two and currently no one ships a native-compatible version of the Compose runtime.

Ultimately the core of Molecule is about 40 lines of code. I would recommend you copy/paste it into your codebase if you have a multiplatform Compose project for now.

**Comment by eygraber** [comment]
It should work since the specific runtime artifact would be used in the context of a matching compiler, and the common Molecule code wouldn't need the compiler because it delegates the composable function to that artifact. 

But yes, copying it would definitely be the easiest solution for now 🙈

**Comment by JakeWharton** [comment]
Molecule itself must be compiled with a compose compiler. Granted, it's probably safe to mix and match the versions used there so long as you always used a newer version, but yeah I'm wary of harming the common case for this rare one.

**Comment by eygraber** [comment]
Ah forgot about the `body` parameters. Oh well, never mind.

**Comment by saket** [comment]
> But aside from Google, JetBrains is the only company which can do this seeing as they currently publish a version of the runtime for JVM and JS

Having multiplatform support would be so nice. Should I file a YouTrack request?

**Comment by JakeWharton** [comment]
You can, although I still think it's unlikely that it will happen.

In order for it to be used here and on Redwood, it would have to be built based on the same SHA that Google uses, rewrite the Gradle metadata to point at Google's artifact for Android, and probably use the same version number (although we do not do the latter for Redwood).

**Comment by antonshilov** [comment]
If I understand it right starting from 1.0.0-beta5 Jetbrains Compose is built with Google(Jetpack Compose) artifacts for Android targets. So it might be possible to use multiplatform and be compatible with Jetpack Compose. Taking info from this comment: https://github.com/JetBrains/compose-jb/issues/1143#issuecomment-964203336

**Comment by ScottPierce** [comment]
Not an ideal scenario, but it seems like `compileOnly` dependencies could work in the short term for this as well.

**Comment by JakeWharton** [comment]
That's right. The `.module` in Maven Central confirms this. Once they publish their 1.1.0 (which appears to be in progress right now) I will update this library to be multiplatform and use their fork.

We are also migrating Redwood to their runtime so that it will no longer build its own either.

However, Google is not off the hook here as it is the one who should be publishing the multiplatform runtime and the Kotlin/Native-targeting version of the compiler. Thankfully, based on some recent CLs going into AOSP, it looks like at the very least they are going to take the JS and native `actual`s for the runtime and move them into AOSP. That's the first step on the road to a Google-published multiplatform Compose runtime.

**Comment by JakeWharton** [comment]
So I found out in upgrading Redwood to Compose 1.1 that _someone_ broke both JS and native support in the Compose runtime/compiler duo. We were forced to jump immediately to the latest 1.2.0 dev builds targeting Google's 1.2.0 alpha binaries.

Since we cannot release this project based on an unstable version, one thing we can do is go multiplatform now but targeting ONLY the JVM and Android. This will unlock Compose for Desktop support which is what I expect 99% of people want anyway.

Then, once 1.2.0 is stable, we can add JS and native targets in for completeness.

**Comment by rocketraman** [comment]
> Since we cannot release this project based on an unstable version, one thing we can do is go multiplatform now but targeting ONLY the JVM and Android. This will unlock Compose for Desktop support which is what I expect 99% of people want anyway.

How about releasing an alpha version based on the 1.2.0 alpha for all platforms? That way you can start getting early feedback from users interested in the JS support.

**Comment by JakeWharton** [comment]
I'm highly skeptical there are JS users who separate their modules enough that they need Molecule. They can, for now, just depend on compose-web and use Molecule as a pattern rather than a library.

**Comment by steve-the-edwards** [comment]
> Since we cannot release this project based on an unstable version, one thing we can do is go multiplatform now but targeting ONLY the JVM and Android. 

Confirming I have the recipe correct for this, use 0.3.0-SNAPSHOT for `molecule` and then ensure we are using the `jetbrains` `1.1.0` compose runtime/compiler and not the androidx targets in our JVM/Android modules as well as the ones that use `molecule` in `common` code?

**Comment by JakeWharton** [comment]
Yes, although it appears snapshot publishing is broken on `trunk` right now, unfortunately.

**Comment by JakeWharton** [comment]
JVM and JS shipped. Support for any native targets is blocked on JetBrains runtime publishing a stable version with native targets. Once they ship, we will ship, too.

**Comment by JakeWharton** [comment]
Re-opening to track other targets.

**Comment by archiegq21** [comment]
Any sample on how to use molecule with KMM? Any additional setup needed other than on the existing documentation?

**Comment by mateuyabar** [comment]
From this issue and docs I understand that Molecule 0.5.0 works on ios targets.
However when I try to build on ios androidx.* libraries are not found.

I've created a sample project with just one molecule (https://github.com/mateuyabar/molecule_ios). Enabling the ios target common/build.gradle.kts on results on a _Unresolved reference: androidx_
Is there still issues with ios?

**Comment by JakeWharton** [comment]
More samples will be coming but there is no timeline on it. In general you just add the plugin and the Compose runtime is automatically made available to use.

**Comment by igorbzin** [comment]
The compose runtime is also available in the shared common modules?

**Comment by JakeWharton** [comment]
It should be, yes, it's a transitive dependency of our runtime library.

**Comment by igorbzin** [comment]
Hi @JakeWharton, I have tried to include the molecule plugin in my KMM project, but even after applying the plugin, it seems that the dependency is not added properly to all sourceSets. I have done some further research and the issue very similar to this issue opened by you: 

https://youtrack.jetbrains.com/issue/KTIJ-18425/

with the difference, that it uses "implementation" instead of "compileOnly". I also don't get the dependency added to my commonMain source set:


<img width="564" alt="Screenshot 2022-11-12 at 10 48 26" src="https://user-images.githubusercontent.com/9799367/201468627-f338538c-e0c9-472f-ac17-c113b0b5a111.png">


 Can you reproduce this behaviour?

**Comment by mateuy-dev** [comment]
@igorbzin  In order to be able to use molecule inside common sources I've added the dependencies manually (as you mentioned plugin was not adding them to common).

```
val commonMain by getting {
       dependencies {
             implementation("app.cash.molecule:molecule-runtime:0.6.0")
             compileOnly("org.jetbrains.compose.compiler:compiler:1.3.2.1")`
(...)
```

**Comment by igorbzin** [comment]
Hi @mateuyabar, thanks for the input. I have already opened an issue https://github.com/cashapp/molecule/issues/136 where the workaround is described as well.

**Comment by archiegq21** [comment]
@JakeWharton Just wondering what's the correct `MonotonicFrameClock` to use for Multiplatform?

**Comment by saket** [comment]
AFAIK `Immediate` is the only option for non-Android targets.

**Comment by JakeWharton** [comment]
It's the only option that is provided, sure. However, you are free to create a `MonotonicFrameClock` for whatever platform-specific mechanism you want. On iOS, for example, you'd probably tie it to `CADisplayLink` if you wanted similar behavior to Android's `Choreographer`.
