### ISSUE TITLE
0.9.0 is missing from Maven Central

### ISSUE THREAD

**Issue by solcott** [cashapp/molecule#220]
It seems that 0.9.0 has recently gone missing from maven central. I updated from 0.8.0 a few days ago.  Yesterday my builds started failing while looking for molecule 0.9.0.  It isn't listed when browsing maven central: https://central.sonatype.com/artifact/app.cash.molecule/molecule-runtime.

**Comment by JakeWharton** [comment]
I see it there: https://repo1.maven.org/maven2/app/cash/molecule/molecule-runtime/0.9.0/

Paste the full error from your build tool.

**Comment by solcott** [comment]
Never mind, looks like it was an issue with multi platform dependencies.  It's weird that 0.9.0 isn't showing up when searching on https://central.sonatype.com/

**Comment by JakeWharton** [comment]
Back when it was search.maven.org it had problems all the time with updating. I assume with their move in infrastructure there's also still growing pains.
