### ISSUE TITLE
README is still referring to RecompositionClock

### ISSUE THREAD

**Issue by mhernand40** [cashapp/molecule#279]
As of [1.0.0](https://github.com/cashapp/molecule/releases/tag/1.0.0):
>`RecompositionClock` is now named `RecompositionMode` to better reflect that it is not itself the clock…

But the README is still referring to `RecompositionClock`.

**Comment by JakeWharton** [comment]
Want to send a PR?

**Comment by mhernand40** [comment]
> Want to send a PR?

Sure
