### ISSUE TITLE
Migrate to Gradle Kotlin DSL

### ISSUE THREAD

**Issue by IAmShaarawy** [cashapp/molecule#286]

**Comment by JakeWharton** [comment]
The README? Or the actual build scripts used within the project?

**Comment by IAmShaarawy** [comment]
both

**Comment by JakeWharton** [comment]
There are no plans to migrate the build scripts of the repo. I would accept a PR to make the Gradle examples in the README compatible with both.

**Comment by IAmShaarawy** [comment]
@JakeWharton Readme is updated within the PR attached to this.
