### ISSUE TITLE
WASM tracking issue

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/molecule#366]
This tracks support for WASM (either or both targets).

Blocked by:
- [x] Stable kotlinx.coroutines with WASM targets
- [x] Stable org.jetbrains.compose.runtime with WASM targets

Once available, we also need to provide a frame clock.

If someone wants to maintain a WIP PR with unstable versions I'd welcome it, but not going to land anything until the runtime targets are stable.

**Comment by ZacSweers** [comment]
By stable WASM targets, does this mean waiting until WASM is completely out of experimental phase? Or could you offer a WASM target in the same way (i.e. "it's experimental just like the upstream deps are")?

**Comment by JakeWharton** [comment]
It means I'm not depending on non-Maven Central repos and non-stable (in a semantic version sense) versions. I think we're probably good to go now with 1.6 being out?

**Comment by ZacSweers** [comment]
Yeah I think so 👍

**Comment by kevincianfarini** [comment]
What would a frame clock use to tick on WASM? Especially on wasi targets

**Comment by JakeWharton** [comment]
The only (Wasm) target that is enabled is JS
