### ISSUE TITLE
RecompositionMode.Immediate with a non-main dispatcher cause ANR while scrolling a LazyColumn (Android)

### ISSUE THREAD

**Issue by j2esu** [cashapp/molecule#396]
According to the docs RecompositionMode.Immediate can be used "for running molecules off the main thread".
When I try to use it with any non-main dispatchers (tried Default, IO, new single thread dispatcher) my app freezes and then gives ANR when I scroll any LazyColumn.
I don't even use the result of molecule to render the list, just any call to molecule affects lazy lists that way.
Please let me know if I'm doing something wrong.

Molecule 1.4.1
Compose compiler 1.5.10
Compose UI 1.6.2
Android SDK 34

MRE:
```kotlin
class MainActivity : ComponentActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        lifecycleScope.launchMolecule(RecompositionMode.Immediate, Dispatchers.Default) { }
        setContent {
            LazyColumn(modifier = Modifier.fillMaxSize()) {
                items(100) {
                    Text(text = "Item $it", modifier = Modifier.padding(16.dp))
                }
            }
        }
    }
}
```

**Comment by JakeWharton** [comment]
Yeah I suspect this is due to the snapshot system and both us and Compose UI launching a coroutine to apply snapshots periodically, but would have to confirm that. It also means that we likely can reproduce this in pure Compose (i.e., no Molecule) and potentially file a bug upstream.

**Comment by JakeWharton** [comment]
I do not have time to look at this any time soon. If no one else does, I'll get to it eventually.

**Comment by jingibus** [comment]
This has also hit us pretty hard at Cash. We're raising the issue with upstream.

**Comment by JakeWharton** [comment]
> It also means that we likely can reproduce this in pure Compose (i.e., no Molecule) and potentially file a bug upstream.

https://issuetracker.google.com/issues/329011032

**Comment by j2esu** [comment]
Tested with [androidx.compose.runtime:runtime:1.7.0-alpha06](https://developer.android.com/jetpack/androidx/releases/compose-runtime#1.7.0-alpha06). Looks fixed to me, no more ANRs.
