### ISSUE TITLE
Migrate to the new JetBrains Compose Gradle + compiler plugin

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/molecule#417]
https://github.com/JetBrains/kotlin/tree/master/plugins/compose
https://github.com/JetBrains/kotlin/tree/master/libraries/tools/kotlin-compose-compiler

And stop maintaining ours

**Comment by aftabahmadTW** [comment]
@JakeWharton just wondering if this is still blocked? Would be great to have a new release of molecule using the updated compiler setup in conjunction with the release of Kotlin 2.0

**Comment by JakeWharton** [comment]
Blocked until 2.0 is stable. I don't have the bandwidth to support two versions at the same time right now.

**Comment by wukaicheng** [comment]
kotlin 2.0 was release

**Comment by JakeWharton** [comment]
https://github.com/cashapp/molecule/pull/450
