### ISSUE TITLE
NoSuchMethodError when using launchMoleculeState with parameters by default

### ISSUE THREAD

**Issue by irymbek** [cashapp/molecule#560]
Thank you for the great work on the Molecule library! It has been really useful in my project. I encountered an issue that I hope you can help resolve.

I encountered an issue when trying to use the launchMoleculeState function in my project, which extends MoleculeViewModel. The function works correctly when called directly using scope.launchMolecule, but when trying to wrap it inside a custom launchMoleculeState method, I get the following error:

> [!NOTE]
 java.lang.NoSuchMethodError: No static method launchMoleculeState$default(Lkz/anilibria/common/utils/viewmodel/MoleculeViewModel;Lapp/cash/molecule/RecompositionMode;Lkotlin/coroutines/CoroutineContext;Lkotlin/jvm/functions/Function2;ILjava/lang/Object;)Lkotlinx/coroutines/flow/StateFlow; in class Lkz/anilibria/common/utils/viewmodel/MoleculeViewModel; or its super classes (declaration of 'kz.anilibria.common.utils.viewmodel.MoleculeViewModel' appears in /data/data/kz.anilibria.app.debug/code_cache/.overlay/base.apk/classes11.dex)
>  

Steps to reproduce:

1. Extend MoleculeViewModel in your ViewModel class.
2. Implement the following custom launchMoleculeState method:

```kotlin
abstract class MoleculeViewModel<State, Event> : ViewModel() {
  private val scope = CoroutineScope(viewModelScope.coroutineContext + AndroidUiDispatcher.Main)

  protected fun <State> launchMoleculeState(
    mode: RecompositionMode = RecompositionMode.ContextClock,
    context: CoroutineContext = Dispatchers.IO,
    body: @Composable () -> State
  ): StateFlow<State> {
    return scope.launchMolecule(
      mode = mode,
      context = context,
      body = body
    )
  }
}
``` 

3. In uiState() method, call launchMoleculeState like this:
```kotlin
override fun uiState(): StateFlow<ReleasesUiState> {
    return launchMoleculeState {
        releasesPresenter(
            releasesFlow = releasesFlow,
            scheduleFlow = scheduleFlow,
            remoteScheduleFlow = remoteScheduleFlow
        )
    }
}
```

The issue can be avoided by using scope.launchMolecule directly, as shown below:
```kotlin
override fun uiState(): StateFlow<ReleasesUiState> {
    return scope.launchMolecule(
        mode = RecompositionMode.ContextClock,
        context = Dispatchers.IO
    ) {
        releasesPresenter(
            releasesFlow = releasesFlow,
            scheduleFlow = scheduleFlow,
            remoteScheduleFlow = remoteScheduleFlow
        )
    }
}
```

Environment:

Kotlin version: 2.1.0
Molecule version: 2.0.0
Gradle version: 8.12

**Comment by JakeWharton** [comment]
In the module which defines `launchMoleculeState` or the module which calls it you are not applying the Compose compiler plugin. It needs to be enabled in both.

For jvm projects, apply the `org.jetbrains.kotlin.plugin.compose` plugin. For Android projects, set `compose = true` in your build features.
