### ISSUE TITLE
Kotlin 1.6 upgrade

### ISSUE THREAD

**Issue by JakeWharton** [cashapp/molecule#66]
Requires a compatible version of Compose

**Comment by krottv** [comment]
Why not to use compose beta?

**Comment by JakeWharton** [comment]
Because we don't want to inflict unstable dependencies on our users.

**Comment by teal77** [comment]
Can we have a pre-release version please? Like how accompanist does it for example.

**Comment by JakeWharton** [comment]
At this point, no. I was out for two months and the stable release should be out any day now. Maybe in the future, though.

**Comment by JakeWharton** [comment]
Released
