### ISSUE TITLE
Allow dispatcher control

### ISSUE THREAD

**Issue by chris-horner** [cashapp/molecule#78]
Not sure this is something that can be addressed easily because of [this coroutines issue](https://github.com/Kotlin/kotlinx.coroutines/issues/2605) noted in `MoleculeTestingTest`, but it would be great for tests that require time manipulation.

**Comment by JakeWharton** [comment]
So in theory this should Just Work™. Perhaps the new `runTest` and associated APIs make the use easier?

Molecule's own tests control time in the dispatcher, although we use now-old APIs: https://github.com/cashapp/molecule/blob/c44a775806b52db88e114d07ef698f6903206c5f/molecule/molecule-runtime/src/commonJvmTest/kotlin/app/cash/molecule/MoleculeTest.kt#L47-L83

**Comment by chris-horner** [comment]
Yep, this does appear to be the case now.

I've run into some annoyances with the very latest coroutine test APIs where [`advanceTimeBy` needs to be called with `runCurrent`](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-test/MIGRATION.md#replace-advancetimebyn-with-advancetimebyn-runcurrent), but it does work 👍
